la longueur : 3 
le nom de l'unité :5 la cible attaquable: 1 sa position: 2 son point de vie: 80 sa vitesse d'attaque: 0.600000 ses degats: 90 sa portee: 1 sa vitesse de deplacement: 3.000000 son posX: 5 son posY: 6 peut_attaquer: 1 son cout en elixir: 1


le nom de l'unité :0 la cible attaquable: 1 sa position: 0 son point de vie: 430 sa vitesse d'attaque: 1.000000 ses degats: 100 sa portee: 3 sa vitesse de deplacement: 0.000000 son posX: 5 son posY: 3 peut_attaquer: 1 son cout en elixir: 0


le nom de l'unité :1 la cible attaquable: 1 sa position: 0 son point de vie: 800 sa vitesse d'attaque: 1.200000 ses degats: 120 sa portee: 4 sa vitesse de deplacement: 0.000000 son posX: 5 son posY: 1 peut_attaquer: 1 son cout en elixir: 0


la longueur : 4 
le nom de l'unité :3 la cible attaquable: 0 sa position: 0 son point de vie: 400 sa vitesse d'attaque: 1.500000 ses degats: 250 sa portee: 1 sa vitesse de deplacement: 2.000000 son posX: 5 son posY: 11 peut_attaquer: 1 son cout en elixir: 4


le nom de l'unité :0 la cible attaquable: 1 sa position: 0 son point de vie: 500 sa vitesse d'attaque: 1.000000 ses degats: 100 sa portee: 3 sa vitesse de deplacement: 0.000000 son posX: 5 son posY: 15 peut_attaquer: 1 son cout en elixir: 0


le nom de l'unité :1 la cible attaquable: 1 sa position: 0 son point de vie: 800 sa vitesse d'attaque: 1.200000 ses degats: 120 sa portee: 4 sa vitesse de deplacement: 0.000000 son posX: 5 son posY: 17 peut_attaquer: 1 son cout en elixir: 0


le nom de l'unité :2 la cible attaquable: 1 sa position: 0 son point de vie: 80 sa vitesse d'attaque: 0.700000 ses degats: 120 sa portee: 3 sa vitesse de deplacement: 1.000000 son posX: 5 son posY: 10 peut_attaquer: 1 son cout en elixir: 2


